name: ue-docker

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install unreal-docker
        run: |
          pip install ue4-docker
          
      - name: Docker config
        run: |
          Get-NetAdapter | Where-Object {$_.Status -eq "Up"}
          Get-DnsClientServerAddress
          nslookup google.com
          # Temporarily disable Windows Firewall to test (be careful in production)
          Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False
          ping google.com
          # Don't forget to re-enable it after testing
          Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled True
          netsh winhttp show proxy
          # --------
          ping google.com
          docker network ls
          Get-NetNat
          docker network inspect nat
          docker run mcr.microsoft.com/windows/nanoserver:1809 ping google.com
          # Remove existing NAT network
          docker network rm nat
          # Create new NAT network
          docker network create --driver="nat" nat
          
      - name: Build Unreal Engine Docker image
        run: |
          ue4-docker setup
          ue4-docker diagnostics network
          # ue4-docker build -basetag ltsc2019 --target minimal --exclude debug --exclude templates --exclude ddc -isolation=process -username=${{ secrets.DOCKER_USERNAME }} -password=${{ secrets.DOCKER_TOKEN }} 4.27.2
