name: ue-docker

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Run Docker stuff
        run: |
          echo ${{ secrets.DOCKER_TOKEN }} | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker run -td --name unreal ghcr.io/tustanivsky/ue-docker-test:4.27
          docker exec unreal git clone https://github.com/getsentry/sentry-unreal.git
          docker exec unreal wget "https://github.com/getsentry/sentry-unreal/releases/download/0.22.0/sentry-unreal-0.22.0-engine4.27-github.zip" -OutFile "sentry.zip"
          docker exec unreal Expand-Archive -Path "sentry.zip" -DestinationPath "sentry-unreal/sample/Plugins" -Force
          docker exec unreal cmd /C "C:\UnrealEngine\Engine\Build\BatchFiles\RunUAT.bat BuildCookRun -project=C:\UnrealEngine\sentry-unreal\sample\SentryPlayground.uproject -archivedirectory=C:\UnrealEngine\sentry-unreal\sample\Builds -platform=Win64 -nop4 -cook -build -stage -prereqss -package -archive"
          docker exec unreal cmd /C "C:\UnrealEngine\Engine\Binaries\Win64\UE4Editor.exe" "C:\UnrealEngine\sentry-unreal\sample\SentryPlayground.uproject" -ReportExportPath="C:\UnrealEngine\sentry-unreal\sample\Saved\Automation" -ExecCmds="Automation RunTests Sentry;quit" -TestExit="Automation Test Queue Empty" -Unattended -NoPause -NoSplash -NullRHI
