name: ue-docker

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install unreal-docker
        run: |
          pip install ue4-docker
          
      - name: Docker config
        run: |
          Set-ItemProperty -Path HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters -Name IPEnableRouter -Value 1
          # Stop Docker
          net stop docker
          # Remove NAT network
          docker network rm nat
          # Recreate NAT network with proper subnet
          docker network create --driver="nat" --subnet=172.28.208.0/20 nat
          # Start Docker
          net start docker
          # Try HTTPS
          Invoke-WebRequest -Uri https://8.8.8.8 -UseBasicParsing
          # Or try a TCP connection
          Test-NetConnection -ComputerName 8.8.8.8 -Port 443
          
      - name: Build Unreal Engine Docker image
        run: |
          ue4-docker setup
          ue4-docker diagnostics network
          # ue4-docker build -basetag ltsc2019 --target minimal --exclude debug --exclude templates --exclude ddc -isolation=process -username=${{ secrets.DOCKER_USERNAME }} -password=${{ secrets.DOCKER_TOKEN }} 4.27.2
