name: ue-docker

on:
  push:
    branches:
      - main  # Change if needed
  workflow_dispatch:  # Allows manual triggering

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: windows-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        if: ${{ steps.exists.outputs.value == 0 }}
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/my-image:latest .

      # - name: Push Image to GHCR
      #   run: |
      #     docker push ghcr.io/${{ github.repository_owner }}/my-image:latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/my-image:latest
          load: false