name: ue-docker

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10'

      # - name: Install unreal-docker
      #   run: |
      #     pip install ue4-docker
          
      - name: Docker config
        run: |
          (Invoke-WebRequest -uri "https://api64.ipify.org").Content
          
      # - name: Build Unreal Engine Docker image
      #   run: |
      #     ue4-docker setup
      #     ue4-docker diagnostics network
      #     # ue4-docker build -basetag ltsc2019 --target minimal --exclude debug --exclude templates --exclude ddc -isolation=process -username=${{ secrets.DOCKER_USERNAME }} -password=${{ secrets.DOCKER_TOKEN }} 4.27.2
