name: ue-docker

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # - name: Install unreal-docker
      #   run: |
      #     pip install ue4-docker
          
      - name: Check out unreal-docker
        uses: actions/checkout@master
        with:
          repository: adamrehn/ue4-docker
          path: ue4-docker

      - name: Install unreal-docker
        run: |
          cd ue4-docker
          pip install . --user
          
      - name: Build Unreal Engine Docker image
        run: |
          ue4-docker setup
          ue4-docker diagnostics network
      #     # ue4-docker build -basetag ltsc2019 --target minimal --exclude debug --exclude templates --exclude ddc -isolation=process -username=${{ secrets.DOCKER_USERNAME }} -password=${{ secrets.DOCKER_TOKEN }} 4.27.2
